### ISSUE TITLE
github 404 on link in Status to https://github.com/cinecert/imf-vtrack-fp

### ISSUE THREAD

**Issue by michaeldsmith** [cinecert/imf-vtfp#2]
I get a github 404 on the first link to documentation/reference-implementation

https://github.com/cinecert/imf-vtrack-fp

**Comment by michaeldsmith** [comment]
![image](https://user-images.githubusercontent.com/37905569/175967081-a3646356-4188-4282-afad-fdd43bebac1e.png)

**Comment by jhursty** [comment]
Fixed in PR #3
